[package]
name = "rustnet"
authors = ["ryanv404"]
description = "An HTTP networking library."
version = "0.1.0"
edition = "2021"
readme = "README.md"
license = "MIT"
repository = "https://github.com/ryanv404/rustnet.git"
keywords = ["http", "server", "client", "networking"]
categories = ["network-programming"]
