name: Compilation and testing checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build check
      run: cargo build --all-targets
    - name: Testing
      run: cargo test --all-targets -- --test-threads=1
